### ISSUE TITLE
Improvements of code readability and reproducibility 

### ISSUE THREAD

**Issue by dorzhey** [noahshanehelton/qPCR_analysis#2]
First of all, surely naming of modules is bit confusing, without domain knowledge and familiarity with the pipeline it can be misleading to have your scripts named "module1", "module2", etc. Project structure just like code structure should represent coding norms, and help both developers and reviewers to navigate through scripts effortlessly.
I like style of your docstrings, but I am afraid this should follow coding norm too - description of function, input (name, data type, optionally meaning), output (name, data type)
qPCR_analysis/module1.py : 
1.  import_and_tidy_data
Calculation of Ct_value does not explicitly handle None values, this can lead to serious errors in downstream analysis
2. primer_efficiency is really good
3. I lack knowledge of what is happening in the rest of the function, so this might be unnecessary, but the rest of the functions seem a little too atomized, i.e. you might be able to integrate some of them in a smaller number of functions.

Most importantly, as I repeated many times, unfortunately the design documents are absent.

**Comment by noahshanehelton** [comment]
Thank you for your feedback. I have updated module names and added design documents. I will incorporate improved docstrings in my code as well as update functions to handle edge cases and exceptions
