### ISSUE TITLE
Code review for plotting functions

### ISSUE THREAD

**Issue by noahshanehelton** [noahshanehelton/qPCR_analysis#4]
Hi Hojae, 

Could you please review my plotting functions and suggest ways to make the graphs objects that can be saved by the user in Plotting.py? Let me know if this is a reasonable request for hw3, thanks! 

Best,
Noah

**Comment by hojaeklee** [comment]
Hi Noah, thanks for the issue. Yes, this is a very doable issue for me. I'll implement and create a pull request for you to review.

**Comment by noahshanehelton** [comment]
Awesome, looks great. Thank you for the advice to change .plt to ax - that makes a lot of sense
